version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: app-php
    image: macartyf/codeflix-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - codeflix-php
  
  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - codeflix-php
networks:
  codeflix-php:
    driver: bridge
